// From nextjs-default (default react template, no example)

import Head from 'next/head'
// import Image from 'next/image'
// import styles from '../css/mineMain.css'

import '../css/mineMain.css'


export default function Home() {
  return (
    <div>
      
      






<head>
    {/* <!-- Meta tags --> */}
    <meta charSet="utf-8"></meta>
    <meta name="viewport" content="width=device-width, initial-scale=1"></meta>
    <title>PFP3</title>

    {/* <!-- Bootstrap CSS (light mode) --> */}
    {/* <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous"></link>  --> */}

    {/* <!-- DARK MODE --> */}
    {/* <!-- SOURCE:  https://github.com/vinorodrigues/bootstrap-dark-5 --> */}
    {/* <!-- Bootstrap CSS (dark mode) --> */}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-dark-5@0.1/dist/css/bootstrap-night.min.css" rel="stylesheet"></link>
    {/* <!-- Locally hosted version --> */}
    {/* <!-- <link href="./css/bootstrap-night.min.css" rel="stylesheet"> --> */}

    {/* <!-- The page supports only a dark color scheme --> */}
    <meta name="color-scheme" content="dark"></meta>


    {/* <!-- Favicon and app icons, generated by realfavicongenerator.net --> */}
    {/* <!-- NOTE:  Change  /images/  to  images/  so it works locally as well --> */}
    {/* <!-- REFERENCE:  https://stackoverflow.com/a/13780457/1263035 --> */}
    <link rel="apple-touch-icon" sizes="180x180" href="images/icons/apple-touch-icon.png"></link>
    <link rel="icon" type="image/png" sizes="32x32" href="images/icons/favicon-32x32.png"></link>
    <link rel="icon" type="image/png" sizes="16x16" href="images/icons/favicon-16x16.png"></link>
    <link rel="manifest" href="images/icons/site.webmanifest"></link>
    <link rel="mask-icon" href="images/icons/safari-pinned-tab.svg" color="#5bbad5"></link>
    <link rel="shortcut icon" href="images/icons/favicon.ico"></link>
    <meta name="msapplication-TileColor" content="#603cba"></meta>
    <meta name="msapplication-config" content="images/icons/browserconfig.xml"></meta>
    <meta name="theme-color" content="#ffffff"></meta>




    {/* <!-- My CSS --> */}
    <link href="./css/mineMain.css" rel="stylesheet"></link>
    {/* <!-- <style></style> --> */}



</head>

<body id="body">


    {/* <!-- Saving message (to hide white flash during save/print css load) --> */}
    {/* <!-- TODO:  Fix/add CSS so the width doesn't create scrollbars --> */}
    <div className="savingMessage startHidden" id="savingMessage">
        <h1 className="text-center">Saving...</h1>
    </div>
    {/* <!--   --> */}




    <div className="container">

        {/* <!-- Header --> */}
        <div className="row pageTitle" id="pageTitle">
            <div className="col-md my-3">
                <h1 className="text-center">Packing for Peanuts</h1>
            </div>
        </div>
        {/* <!--   --> */}







        {/* <!-- FUNCTION:  Show results upon form submit (and hide rest of page) --> */}
        {/* <!-- Start hidden, only show after hitting submit  --> */}
        {/* <!-- TITLE:  Results box --> */}
        <div className="startHidden resultsBoxContainer" id="resultsBoxContainer">
            {/* <!-- Don't show title during print --> */}
            <div className="row resultsBoxTitle d-print-none" id="resultsBoxTitle">
                <div className="col-md my-3">
                    <h2>Packing Results:</h2>
                </div>
            </div>
            <div className="row">
                {/* <!-- NOTE:  The text here is sent from javascript using <br /> line breaks --> */}
                <div className="col-md mb-3 resultsBox" id="resultsBox">
                    Sample
                </div>
            </div>
            {/* <!-- TIP:  Boostrap class  .d-print-none  hides this during printing--> */}
            {/* <!-- REFERENCE:  https://stackoverflow.com/a/36352263 --> */}
            {/* <!-- REFERENCE:  https://getbootstrap.com/docs/5.0/utilities/display/#display-in-print --> */}
            <div className="row d-print-none">
                <form id="resultsForm">
                    {/* <!-- FORM FOOTER --> */}
                    <div className="row mb-3">
                        <div className="col">
                            {/* <!-- FUNCTION:  Back button (calls the showMainPage function which inverts the display of elements shown/hidden by the showResults function) --> */}
                            {/* <!-- TIP:  Align right with float-end --> */}
                            {/* <!-- Source for arrows:  https://www.calculators.org/math/html-arrows.php --> */}
                            <button type="button" className="btn btn-secondary mb-1 backButton" id="backButton">← Go
                                Back &nbsp;</button>
                            {/* <!-- FUNCTION:  This "submit" button isn't actually submitting anything, but it refreshes the page on submit, which is the goal  --> */}
                            {/* <!-- TODO:  Maybe change this from a submit button to a refresh page button (like my custom reset button). No real reason to as of now though --> */}
                            {/* <!-- TIP:  Align right with float-end --> */}
                            <button type="submit" className="btn btn-warning mb-1 float-left submitButton"
                                id="resultsSubmitButton">↺ Start Over &nbsp;</button>
                        </div>

                        <div className="col">
                            {/* <!-- FUNCTION:  Print button --> */}
                            {/* <!-- TIP:  Align right with float-end or float-right--> */}
                            {/* <!-- reordered these buttons since the first floats to the end/right --> */}
                            {/* <!-- removed  onClick="window.print()"  and moved it to the SO# validation function upon clicking print --> */}
                            <input type="button" className="btn btn-primary mb-1 mx-1 float-end printButton"
                                id="printButton" value="⎙ Print"></input>

                            {/* <!-- FUNCTION:  Save pdf button (using html2pdf, in scripts) --> */}
                            <input type="button" className="btn btn-secondary mb-1 mx-1 float-end printButton"
                                id="saveButton" value="🖫 Save"></input>
                        </div>
                    </div>
                </form>
            </div>
        </div>














        {/* <!-- To toggle a class of divs shown/hidden (without issues), don't use bootstrap collapse (which alternates toggled elements), just use display:none / block

        {/* <!-- 
        To make other sections collapse when one expands:
        For Bootstrap5      Add the  data-bs-parent="#customParentID"  attribute to the collapse elements instead of the button.
        https://stackoverflow.com/questions/11476670/bootstrap-collapse-other-sections-when-one-is-expanded
        --> */}
        {/* <!-- TIP:  My non-bootstrap  className="startHidden"  to start hidden --> */}
        {/* <!-- TIP:  Bootstrap  className="collapse"  to start hidden,  className="collapse.show"  to start shown  (i'm not using collapse anymore)--> */}
        {/* <!-- TODO:  Hide/collapse all of this group before showing parts of the group. might need to remove data bs toggle true and parent --> */}
        {/* <!-- BUG:  Adding gap on parent div requires me to click a button twice for it to show content the first time... --> */}
        {/* <!-- HISTORY:  I was trying to use the bootstrap 5 collapse command, but it wouldn't let me hide everything i want before showing only what I want --> */}
        {/* <!--  it would only toggle states, so half of the ones you want to show would disappear if there was overlap and you clicked a different button --> */}
        {/* <!--  so I switched to HTML+Javascript  display='none'  and display=''  (to reset it to showing)  --> */}
        {/* <!--  (might have to invert this if i don't want everything showing at the start. maybe set it to block or inline instead of ''?) --> */}
        {/* <!-- REFERENCE:  https://www.w3schools.com/howto/howto_js_toggle_hide_show.asp --> */}

        {/* <!-- BEHAVIOR:  onclick, it runs the javascript function  collapseGroup, and sends the name of the group/class to expand as an argument --> */}
        {/* <!-- TIP:  Add a class name (like groupLds) to every element in a group you want shown (when clicking a header button), since comma-separated IDs didn't work --> */}

        {/* <!-- BEHAVIOR:  onsubmit="return false"  was added to prevent the page refresh on submit, so I can show the results --> */}
        {/* <!-- REFERENCE:  https://stackoverflow.com/a/57226770 --> */}
        {/* <!-- TODO:  Add a Reset/Continue/Clear/Start Over button to the results (as well as a Print button, defaulting to 4x6 and zebra printer) --> */}

        <form id="mainForm" onSubmit="return false">
            <div id="wizard1">
                <div className="row mb-4">
                    <div className="btn-group" role="group" aria-label="Select type of system being sent">

                        {/* <!-- HISTORY:  To set one to default true/active, add  checked  somewhere. Adding  className="active"  didn't work --> */}
                        {/* <!-- REFERENCE:  https://getbootstrap.com/docs/5.0/components/button-group/#checkbox-and-radio-button-groups --> */}
                        {/* <!-- System: LDS Valve  radio button--> */}
                        {/* <!-- <input type="radio" className="btn-check active" checked name="btnradio" id="btnradio1" --> */}
                        <input type="radio" className="btn-check" name="btnradio" id="btnradio1" data-bs-toggle="true"
                            onClick="collapseGroup('groupLds')" autocomplete="off" aria-expanded="true"
                            aria-controls=".groupLds" value="1"></input>
                        <label className="btn btn-primary" for="btnradio1">System:&nbsp; LDS Valve</label>

                        {/* <!-- System: POLD-Only  radio button --> */}
                        <input type="radio" className="btn-check" name="btnradio" id="btnradio2" data-bs-toggle="false"
                            onClick="collapseGroup('groupPoldOnly'); setLds(0);" autocomplete="off"
                            aria-expanded="false" aria-controls=".groupPoldOnly" value="2"></input>
                        <label className="btn btn-primary" for="btnradio2">System:&nbsp; POLD-Only</label>

                        {/* <!-- Accessories Only  radio button --> */}
                        <input type="radio" className="btn-check" name="btnradio" id="btnradio3" data-bs-toggle="false"
                            onClick="collapseGroup('groupAccessories'); setLds(0);" autocomplete="off"
                            aria-expanded="false" aria-controls=".groupAccessories" value="3"></input>
                        <label className="btn btn-primary" for="btnradio3">Accessories Only</label>
                    </div>
                </div>
                {/* <!-- Everything with class  groupWizard1  gets hidden first, upon header click  (like it's the 1st wizard step) --> */}
                <div className="row mb-4 groupWizard1">
                    <p className="text-center">Select one of the 3 options above to start.</p>
                </div>




                {/* <!-- FUNCTION:  Wrap everything in a  startHidden  div to start collapsed before showing with top 3 toggles  (div 1 of 2)--> */}
                <div className="startHidden showOnHeaderClick">


                    {/* <!-- SYSTEM: LDS --> */}
                    {/* <!-- TODO:  Change class collapse.show to collapse to hide by default after programming/testing is done --> */}
                    {/* <!-- TIP:  Change className="row collapse  back to  className="row collapse.show  to start shown on page load --> */}
                    <div className="row collapse.show groupWizard1 ldsBox groupLds groupAccessories" id="ldsBox">

                        {/* <!-- TODO:  form className="mx-3" but make it actually work to shrink the box on the right end as well instead of overflow --> */}
                        {/* <!-- Example from:  https://getbootstrap.com/docs/5.0/forms/overview/ --> */}


                        {/* <!-- These group div classes are to hide or show certain divs depending on which header button is selected --> */}
                        <div className="row groupWizard1 groupLds groupAccessories">
                            <div className="col groupWizard1 groupLds">
                                {/* <!--  TODO:  Change valueLds to number of LDS, then add valueLdsSize for size? (hardcoded to 1 LDS in scripts) --> */}
                                <label for="selectLds" className="form-label">LDS Valve Size</label>
                                {/* <!-- Auto-include SCV of same size --> */}
                                {/* <!-- Auto-include CP, 12V PSU --> */}
                                <select className="form-select" id="selectLds">
                                    <option selected></option>
                                    <option value="0.75">0.75"</option>
                                    <option value="1.00">1.00"</option>
                                    <option value="1.25">1.25"</option>
                                    <option value="1.50">1.50"</option>
                                    <option value="2.00">2.00"</option>
                                    <option value="2.50">2.50"</option>
                                    <option value="3.00">3.00"</option>
                                </select>
                            </div>
                            <div className="col groupWizard1 groupLds groupAccessories">
                                <label for="inputScv" className="form-label"><i>Spring Check Valve</i></label>
                                <input type="number" className="form-control" id="inputScv" aria-describedby="scvHelp"></input>
                            </div>
                        </div>


                        {/* <!-- Split system --> */}
                        <div className="row">
                            <div className="col mt-2 groupWizard1 groupLds">
                                {/* <!-- Split system checkbox --> */}
                                <div className="form-check">
                                    {/* <!-- Supposed to have  form-check  class on parent div, but that puts checkbox on left. Remove if you want checkbox on right --> */}
                                    <label for="checkSplitSystem" className="form-label mx-3">Split System</label>
                                    {/* <!-- TODO:  Align checkbox right (keeping text and div section on left) --> */}
                                    <input type="checkbox" className="form-check-input mx-1" id="checkSplitSystem"></input>
                                </div>
                            </div>
                            {/* <!-- Spring Check Valve description --> */}
                            <div className="col mb-2">
                                <div id="scvHelp" className="form-text"><i>1 is included with an LDS by default.</i></div>
                            </div>
                        </div>
                        {/* <!-- Split system dropdown --> */}
                        <div className="row mb-2">
                            <div className="col">
                                {/* <!--  TODO:  Change valueLds to number of LDS, then add valueLdsSize for size? (hardcoded to 1 LDS in scripts) --> */}
                                {/* <!-- <label for="selectSplitSystem" className="form-label">Split System Size</label> --> */}
                                {/* <!-- Auto-include SCV of same size --> */}
                                {/* <!-- Auto-include CP, 12V PSU --> */}
                                <select className="form-select startHidden mb-2" id="selectSplitSystem">
                                    <option selected></option>
                                    <option value="1">B1</option>
                                    <option value="2">B2</option>
                                    <option value="3">B3 (tentative logic)</option>
                                </select>
                            </div>
                            <div className="col">
                            </div>
                        </div>

                    </div>




                    {/* <!-- SYSTEM: POLD-ONLY --> */}

                    {/* <!-- Control Panel --> */}
                    <div className="row collapse.show groupWizard1 poldOnlyBox groupLds groupPoldOnly groupAccessories"
                        id="poldOnlyBox">
                        <div className="mb-3">
                            <label for="inputCp" className="form-label">Control Panel</label>
                            <input type="number" className="form-control" id="inputCp"></input>
                        </div>
                    </div>

                    {/* <!-- Hidden Wire --> */}
                    {/* <!-- TODO:  Checkbox checked state not visible when using chrome dark mode extension --> */}
                    {/* <!-- Supposed to have  form-check  class on parent div, but that puts checkbox on left. Remove if you want checkbox on right --> */}
                    <div className="row mb-4">
                        <div className="mb-0 form-check">
                            <label for="checkHiddenWire" className="form-label mx-3">Hidden Power Wire (Control
                                Panel)</label>
                            {/* <!-- TODO:  Align checkbox right (keeping text and div section on left) --> */}
                            <input type="checkbox" className="form-check-input mx-1" id="checkHiddenWire"></input>
                            <input type="number" className="form-control startHidden" value="10" id="inputHiddenWireLength"></input>
                            <div id="hiddenWireHelp" className="form-text startHidden"><i>Ft.</i></div>
                        </div>
                    </div>



                    {/* <!-- ACCESSORIES --> */}
                    <div className="row collapse.show groupWizard1 accessoriesBox groupLds groupPoldOnly groupAccessories"
                        id="accessoriesBox">


                        {/* <!-- Instruction text --> */}
                        {/* <!-- font-weight-bold isn't working... --> */}
                        <div className="mt-3 mb-3 font-weight-bold"><b>Enter the amount of each accessory:</b></div>

                        {/* <!-- API --> */}
                        <div className="mb-3">
                            {/* <!-- value="1" to default to 1. min="0" max="30" for min and max --> */}
                            <label for="inputApi" className="form-label">APIs</label>
                            <input type="number" className="form-control" id="inputApi" min="0" max="30"
                                aria-describedby="apiHelp"></input>
                            <div id="apiHelp" className="form-text"><i>Maximum of 30.</i></div>
                        </div>

                        {/* <!-- POLDs --> */}
                        {/* <!-- div class mb-3 is margin-bottom --> */}
                        {/* <!-- Used mx-0 to fix this bootstrap row from sliding to the left --> */}
                        {/* <!-- REFERENCE:  https://getbootstrap.com/docs/4.0/layout/grid/ --> */}
                        {/* <!--   "Columns have horizontal padding to create the gutters between individual columns,""  --> */}
                        {/* <!--   "however, you can remove the margin from rows and padding from columns with .no-gutters on the .row." (didn't work) --> */}
                        <div className="row mx-0">
                            {/* <!-- Removed left padding on text with px-0 --> */}
                            <div className="col-sm-auto px-0">
                                <label for="inputPold" className="form-label" id="inputPoldLabel">POLDs</label>
                            </div>
                            <div className="col-auto">
                                {/* <!-- Checkbox for auto-calculating POLD total --> */}
                                <div className="form-check startHidden divCalcPoldTotal" id="divCalcPoldTotal">
                                    {/* <!-- Supposed to have (bootstrap)  form-check  class on parent div, but that puts checkbox on left. Remove if you want checkbox on right --> */}
                                    <label for="checkCalcPoldTotal" className="form-label mx-3"><i>Auto-calculate POLD
                                            total</i></label>
                                    <input type="checkbox" className="form-check-input mx-1" id="checkCalcPoldTotal"></input>
                                </div>
                            </div>
                        </div>
                        <div className="row mb-2 mx-0">
                            {/* <!-- POLD number input --> */}
                            <input type="number" className="form-control" id="inputPold" min="0" max="30"
                                aria-describedby="poldHelp"></input>
                            <div id="poldHelp" className="form-text"><i>If requesting more than 15, email a
                                    list of zones. If more than 30, contact warehouse.</i>
                            </div>
                        </div>

                        {/* <!-- Leak Rope --> */}
                        <div className="row">
                            <div className="col mt-0">
                                {/* <!-- Leak Rope checkbox --> */}
                                <div className="form-check">
                                    {/* <!-- Supposed to have (bootstrap)  form-check  class on parent div, but that puts checkbox on left. Remove if you want checkbox on right --> */}
                                    <label for="checkLeakRope" className="form-label mx-3">Leak Rope</label>
                                    {/* <!-- TODO:  Align checkbox right (keeping text and div section on left) --> */}
                                    <input type="checkbox" className="form-check-input mx-1" id="checkLeakRope"></input>
                                </div>
                            </div>
                            {/* <!-- Extra column for the heck of it --> */}
                            <div className="col">
                            </div>
                        </div>
                        {/* <!-- Leak rope options --> */}
                        <div className="row mx-1 mt-2">
                            <div className="col mx-1 mb-2 startHidden expandPold" id="expandPold1">
                                <label for="inputPoldPin" className="form-label">POLDs with pins</label>
                                <input type="number" className="form-control" id="inputPoldPin" min="0" max="30"></input>
                            </div>
                            {/* <!-- Extra column for the heck of it --> */}
                            <div className="col">
                            </div>
                        </div>

                        <div className="row mb-4">
                            {/* <!-- POLD with Leak Rope --> */}
                            <div className="col startHidden expandPold" id="expandPold2">
                                <div className="card m-3">
                                    <div className="m-3">
                                        <label for="inputPoldLeakRope2ft" className="form-label">POLDs with Leak Rope
                                            (2ft)</label>
                                        <input type="number" className="form-control" id="inputPoldLeakRope2ft" min="0"
                                            max="30"></input>
                                    </div>
                                    <div className="m-3">
                                        <label for="inputPoldLeakRope5ft" className="form-label">POLDs with Leak Rope
                                            (5ft)</label>
                                        <input type="number" className="form-control" id="inputPoldLeakRope5ft" min="0"
                                            max="30"></input>
                                    </div>
                                    <div className="m-3">
                                        <label for="inputPoldLeakRope10ft" className="form-label">POLDs with Leak Rope
                                            (10ft)</label>
                                        <input type="number" className="form-control" id="inputPoldLeakRope10ft" min="0"
                                            max="30"></input>
                                    </div>
                                </div>
                            </div>
                            {/* <!-- Just Leak Rope --> */}
                            <div className="col startHidden expandPold" id="expandPold3">
                                <div className="card m-3">
                                    <div className="m-3">
                                        <label for="inputLeakRope2ft" className="form-label">Just Leak Rope (2ft)</label>
                                        <input type="number" className="form-control" id="inputLeakRope2ft" min="0"
                                            max="30"></input>
                                    </div>
                                    <div className="m-3">
                                        <label for="inputLeakRope5ft" className="form-label">Just Leak Rope (5ft)</label>
                                        <input type="number" className="form-control" id="inputLeakRope5ft" min="0"
                                            max="30"></input>
                                    </div>
                                    <div className="m-3">
                                        <label for="inputLeakRope10ft" className="form-label">Just Leak Rope (10ft)</label>
                                        <input type="number" className="form-control" id="inputLeakRope10ft" min="0"
                                            max="30"></input>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>





                    {/* <!-- Hidden input field for largePSU, to keep logic working the same --> */}
                    <div className="mt-5 mb-3 startHidden groupWizard1 groupLds groupAccessories">
                        <label for="inputLargePSU" className="form-label">Large PSU (24V Power Supply w/Enclosure)</label>
                        <input type="number" className="form-control" id="inputLargePSU"></input>
                    </div>



                    <div className="mb-3 groupWizard1 groupLds groupAccessories">
                        <label for="inputRecirc" className="form-label">Recirculation Pump Switch</label>
                        <input type="number" className="form-control" id="inputRecirc"></input>
                    </div>
                    <div className="mb-3 groupWizard1 groupLds groupAccessories">
                        <label for="inputFourHour" className="form-label">Four Hour Timer</label>
                        <input type="number" className="form-control" id="inputFourHour"></input>
                    </div>
                    {/* <!-- Why does this not have  className="mb-3 groupWizard1 groupLds groupAccessories"  ?  I guess to always show, even on pold-only? --> */}
                    <div className="mb-3">
                        <label for="inputPam1" className="form-label">PAM-1 Relay</label>
                        <input type="number" className="form-control" id="inputPam1"></input>
                    </div>
                    {/* <!-- Why does this not have  className="mb-3 groupWizard1 groupLds groupAccessories"  ?  I guess to always show, even on pold-only? --> */}
                    <div className="mb-3">
                        <label for="inputSsr" className="form-label">Solid State Relay</label>
                        {/* <!-- If you want to constrain to even numbers and fail validation if not:  step="2" --> */}
                        <input type="number" className="form-control" id="inputSsr" step="2"></input>
                        <div id="ssrHelp" className="form-text"><i>Typically sent in multiples of 2.</i></div>
                    </div>



                    <div className="mt-5 mb-3 groupWizard1 groupLds groupAccessories">
                        <label for="inputJuncBox" className="form-label">Junction Box</label>
                        <input type="number" className="form-control" id="inputJuncBox"></input>
                    </div>
                    {/* <!-- Don't show if POLD-Only is selected (through the group classes, only for lds and accessories) --> */}
                    <div className="mb-3 groupWizard1 groupLds groupAccessories">
                        <label for="inputInsulPouch" className="form-label">Insulated Pouch</label>
                        <input type="number" className="form-control" id="inputInsulPouch"></input>
                    </div>


                    {/* <!-- Spacing --> */}
                    <div className="mt-4 mb-3">&nbsp;</div>
                    {/* <!-- Horizontal line --> */}
                    <hr>
                    {/* <!-- Instruction text --> */}
                    <div className="mt-3 mb-3"><b>Extra info:</b></div>

                    {/* <!-- SO#  (to keep track of multiple pages together, and matching printed labels to packing lists etc) --> */}
                    {/* <!-- Input not required, and won't print if value is not greater than 0/blank --> */}
                    {/* <!-- I think I lost my form validation when I made form return false to prevent refreshing the page --> */}
                    {/* <!-- Could add an eventlistener if I really wanna validate this form input --> */}
                    {/* <!-- I set the max to 999999999999999 because after this, it truncates it weirdly --> */}
                    <div className="mb-4 mt-3">
                        <label for="inputSoNum" className="form-label">Sales Order Number (SO#)</label>
                        <input type="number" className="form-control" id="inputSoNum" min="0" max="999999999999999"
                            aria-describedby="soNumHelp"></input>
                        <div id="soNumHelp" className="form-text"><i>Only required if printing labels for a multi-box
                                shipment</i></div>
                    </div>

                </div>

            </div>



            {/* <!-- FORM FOOTER --> */}
            {/* <!-- FUNCTION:  Wrap everything in a  startHidden  div to start collapsed before showing with top 3 toggles  (div 2 of 2)--> */}
            <div className="startHidden showOnHeaderClick">
                <div className="row collapse.show groupWizard1 formFooterBox groupLds groupPoldOnly groupAccessories"
                    id="formFooterBox">
                    {/* <!-- font-weight-bold isn't working... --> */}
                    {/* <!-- TODO: Expand to show extra input fields like zoho link, device id, details/comment box to help person preparing (and maybe auto copy to zoho and packing list/label?) --> */}

                    <div className="mb-3 form-check">
                        <input type="checkbox" className="form-check-input mx-3" id="checkReplacement"></input>
                        <label className="form-check-label" for="checkReplacement">Replacement for existing
                            system/accessory?</label>
                    </div>


                    <div className="row mt-1 mb-2">
                        <div className="col">
                            <div className="resetAndSubmitButtons" id="resetAndSubmitButtons">
                                {/* <!-- FUNCTION:  Reset button --> */}
                                {/* <!-- HISTORY:  Wasn't fully resetting the form, so I switched to just refreshing the page on click --> */}
                                {/* <!-- REFERENCE:  https://stackoverflow.com/a/20740876/1263035 --> */}
                                {/* <!-- Also added scrolling back to top of page --> */}
                                {/* <!-- REFERENCE:  https://stackoverflow.com/a/66789888/1263035 --> */}
                                <button className="btn btn-danger btn-sm mx-2 " type="reset" id="mainResetButton"
                                    value="Reset">Reset</button>
                                {/* <!-- Wasn't fully resetting the form, so I was manually hiding shown divs as well with  onClick="resetHidden()" but now just refreshing page --> */}
                                {/* <!-- <button className="btn btn-danger btn-sm" type="reset" id="mainResetButton"
                                    onClick="resetHidden()" value="Reset">Reset</button> --> */}

                                {/* <!-- FUNCTION:  Submit button --> */}
                                {/* <!-- TIP:  Align right with float-end --> */}
                                <button type="submit" className="btn btn-primary submitButton"
                                    id="finalSubmitButton">Submit</button>
                            </div>
                        </div>
                        <div className="col">
                            {/* <!-- Submit button used to be here on the right --> */}
                            {/* <!-- May not actually need the rows and columns now --> */}
                        </div>
                    </div>

                    <div className="mt-3">
                        <div className="float-end">
                            {/* <!-- VERSION number --> */}
                            {/* <!-- Text is not aligning right and idk why --> */}
                            <div className="">
                                <p className="versionNumber text-muted text-right" id="versionNumber"><i>Version 3.3.1</i>
                                </p>
                            </div>
                            <div className="mb-3 form-check startHidden" id="debugDiv">
                                {/* <!-- float-end  for align-right --> */}
                                <input type="checkbox" className="form-check-input mx-3" id="checkDebug"></input>
                                <label className="form-check-label text-muted" for="checkDebug"><i>[Debugging
                                        mode]</i></label>
                            </div>
                            <div className="mb-3 startHidden" id="knownIssues">
                                {/* <!-- REFERENCE: https://stackoverflow.com/a/17711167  rel="noopener noreferrer" to prevent phishing attacks --> */}
                                {/* <!-- float-end  for align-right --> */}
                                <a href="z_todo.txt" className="mx-3" target="_blank" rel="noopener noreferrer"><i>[Known
                                        issues]</i></a>
                            </div>
                        </div>
                    </div>

                </div>

            </div>


        </form>

    </div>





























    {/* <!-- JAVASCRIPT --> */}



    {/* <!-- Bootstrap 5 Bundle with Popper --> */}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous">
    </script>
    {/* <!-- Locally hosted version --> */}
    {/* <!-- <script src="./js/bootstrap5.0.0-beta2-w-popper_bootstrap.bundle.min.js"
        integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous">
    </script> --> */}





    {/* <!-- Luxon javascript library for working with dates/times (using for pdf filename generation) --> */}
    {/* <!-- SOURCE:  https://moment.github.io/luxon/ --> */}
    {/* <!-- SOURCE:  https://github.com/moment/luxon/ --> */}
    {/* <!-- Day.js is another simpler alternative with easier customization.  https://day.js.org/docs/en/parse/string-format --> */}
    {/* <!-- Other datetime library options listed here:  https://momentjs.com/docs/#/-project-status/ --> */}
    <script src="./js/luxon.min.js"></script>



    {/* <!-- Generating a datetime variable for pdf filename generation, using Luxon library --> */}
    <script type="text/javascript" src="./js/myjs/luxonDateTimeFunc.js">
    </script>






    {/* <!-- HISTORY:  jsPDF wasn't working so I used html2pdf.js --> */}
    {/* <!-- jsPDF library for generating pdf.  https://github.com/MrRio/
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.3.1/jspdf.es.min.js"></script> --> */}

    {/* <!-- jsPDF CREATE PDF (my code / page formatting) --> */}
    {/* <!-- <script src="./js/myjs/jsPdfCreatePdf.js"></script> --> */}






    {/* <!-- SAVE PDF. html2pdf library for generating pdf.  https://github.com/eKoopmans/html2pdf.js --> */}
    <script src="./js/html2pdf.bundle.min.js"></script>

    {/* <!-- To enable png image compression, try using the canvas-png-compression shim,   // Didn't work, disabled
     which should be an in-place solution to enable png compression via the quality option.
     SOURCE:  https://github.com/ShyykoSerhiy/canvas-png-compression --> */}
    {/* <!-- <script src="./js/canvas-png-compression_bundle.js"></script>  Didn't work, disabled --> */}



    {/* <!-- SAVE PDF --> */}
    <script type="text/javascript" src="./js/myjs/savePdf.js">
    </script>










    {/* <!-- Custom scripts --> */}
    <script type="text/javascript" src="./js/myjs/main.js">
    </script>

</body>





















    </div>
  )
}
